apiVersion: v1
kind: Pod
metadata:
  name: hello-nodejs-pod
  labels:
    app: hello-nodejs
spec:
  containers:
  - name: hello-nodejs-k8s-demo
    image: mulethunder/hello-microservices-k8s
    ports:
    - name: nodejs-port
      containerPort: 3000