---
apiVersion: v1
kind: Service
metadata:
  name: hello-nodejs-svc
  namespace: hello-microservices
spec:
  type: NodePort
  ports:
  - name: http
    targetPort: 3000
    port: 3000
  selector:
    app: hello-nodejs
    microservice: app